dcfldd_error: drop program_invocation_name support
dcfldd_error() is meant to replace only error() invocations within the
dcfldd codebase. Full glibc compliance is not a goal.

Thus, this drops the (incomplete) program_invocation_support, while
better commenting the differences from glibc's error().